apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-da84
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-da84
    app.kubernetes.io/part-of: tkwch-fix-0075-0068-app
  name: devfile-sample-da84
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-da84
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-da84
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-6-tenant/tkwch-fix-0075-0068-app/devfile-sample-da84@sha256:6098328b8e5c3a0c47198d2e6e1febf37136b60ba5e2c40b44ea9e5d8e7531a3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
