apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-da84
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-6-tenant/tkwch-fix-0075-0068-app/devfile-sample-da84@sha256:6098328b8e5c3a0c47198d2e6e1febf37136b60ba5e2c40b44ea9e5d8e7531a3
        name: my-nodejs
        resources: {}
status: {}
